name: CI/CD Pipeline for Spring Boot Application

on:
  push:
    branches-ignore:
      - development
      - staging
      - production

  pull_request:
    branches:
      - development
      - staging
      - production

jobs:
  validate-pr-source:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Validate PR source
        run: |
          BASE="${{ github.event.pull_request.base.ref }}"
          HEAD="${{ github.event.pull_request.head.ref }}"
          echo "Base branch: $BASE"
          echo "Head branch: $HEAD"
          
          # Autoriser uniquement development vers staging
          if [ "${{ github.base_ref }}" == "staging" ] && [ "${{ github.head_ref }}" != "development" ]; then
            echo "❌ Seul 'development' peut faire un PR vers 'staging'"
            exit 1
          fi
          
          # Autoriser uniquement staging vers production
          if [ "${{ github.base_ref }}" == "production" ] && [ "${{ github.head_ref }}" != "staging" ]; then
            echo "❌ Seul 'staging' peut faire un PR vers 'production'"
            exit 1
          fi
          
          echo "✅ Validation réussie"
  lint:
    needs: validate-pr-source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run Checkstyle
        run: mvn checkstyle:check

  tests:
    needs: validate-pr-source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run unit tests
        run: mvn test -Punit-tests

